# Generated by Django 4.2.16 on 2024-10-27 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('medical_records_app', '0003_alter_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.doctor')),
                ('original_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='medical_records_app.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient')),
            ],
        ),
    ]
