# Generated by Django 4.2.16 on 2024-10-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records_app', '0004_medicalrecordarchive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecordarchive',
            options={'ordering': ['-version']},
        ),
    ]
